export const QUERY_KEYS = {
  ARTICLE_ANALYTICS: "ARTICLE_ANALYTICS",
  ARTICLE: "ARTICLE",
  ARTICLES_COUNT: "ARTICLES_COUNT",
  ARTICLE_SEARCH_RESULTS: "ARTICLE_SEARCH_RESULTS",
  GENERATE_PDF: "GENERATE_PDF",
  DOWNLOAD_PDF: "DOWNLOAD_PDF",
  CATEGORIES: "CATEGORIES",
  CATEGORY_SEARCH: "CATEGORY_SEARCH",
  SITE: "SITE",
  REDIRECTIONS: "REDIRECTIONS",
};
